import {IActualite} from "@/features/actualite/types/actualite.type";

export const articlesFakeData: IActualite[] = [
	{
		id: "1",
		titre: "Nouvelle application de prière lancée",
		image: "/assets/effata/articles/article1.png",
		slug: "nouvelle-application-de-priere-lancee",
		date_publication: "2024-06-01",
		category: "Technologie",
		country: "France",
		authorName: "Jean Dupont",
		tags: ["application", "prière", "lancement"],
		description: "Salutation du Saint-Père au Patriarche bouddhiste le jeudi 21 novembre 2019 au Temple Wat Ratchabophit Sathit Maha Simaram (Bangkok).",
	},
	{
		id: "2",
		titre: "Conférence sur l'innovation religieuse",
		image: "/assets/effata/articles/article10.jpg   ",
		slug: "conference-innovation-religieuse",
		date_publication: "2024-06-05",
		category: "Événement",
		country: "Belgique",
		authorName: "Marie Lambert",
		tags: ["conférence", "innovation", "religion"],
	},
	{
		id: "3",
		titre: "Lancement d'un podcast chrétien",
		image: "/assets/effata/articles/article3.jpeg",
		slug: "lancement-podcast-chretien",
		date_publication: "2024-06-10",
		category: "Média",
		country: "Suisse",
		authorName: "Paul Martin",
		tags: ["podcast", "chrétien", "audio"],
	},
	// 7 autres actualités avec des id uniques
	{
		id: "4",
		titre: "Actualité 4",
		image: "/assets/effata/articles/article4.jpg",
		slug: "#",
		date_publication: "2024-06-11",
		category: "Média",
		country: "Suisse",
		authorName: "Paul Martin",
		tags: ["tag1"],
	},
	{
		id: "5",
		titre: "Actualité 5",
		image: "/assets/effata/articles/article5.jpg",
		slug: "#",
		date_publication: "2024-06-12",
		category: "Média",
		country: "Suisse",
		authorName: "Paul Martin",
		tags: ["tag1"],
	},
	{
		id: "6",
		titre: "Actualité 6",
		image: "/assets/effata/articles/article6.png",
		slug: "#",
		date_publication: "2024-06-13",
		category: "Média",
		country: "Suisse",
		authorName: "Paul Martin",
		tags: ["tag1"],
	},
	{
		id: "7",
		titre: "Actualité 7",
		image: "/assets/effata/articles/article7.jpg",
		slug: "#",
		date_publication: "2024-06-14",
		category: "Média",
		country: "Suisse",
		authorName: "Paul Martin",
		tags: ["tag1"],
	},
	{
		id: "8",
		titre: "Actualité 8",
		image: "/assets/effata/articles/article8.jpeg",
		slug: "#",
		date_publication: "2024-06-15",
		category: "Média",
		country: "Suisse",
		authorName: "Paul Martin",
		tags: ["tag1"],
	},
	{
		id: "9",
		titre: "Actualité 9",
		image: "/assets/effata/articles/article9.jpg",
		slug: "#",
		date_publication: "2024-06-16",
		category: "Média",
		country: "Suisse",
		authorName: "Paul Martin",
		tags: ["tag1"],
	},
	{
		id: "10",
		titre: "Actualité 10",
		image: "/assets/effata/articles/article1.png",
		slug: "#",
		date_publication: "2024-06-17",
		category: "Média",
		country: "Suisse",
		authorName: "Paul Martin",
		tags: ["tag1"],
	},
];
