import { IActualite } from "@/features/actualite/types/actualite.type";

export const articlesFakeData: IActualite[] = [
  {
    id: "1",
    title: "Nouvelle application de prière lancée",
    image: "/assets/effata/articles/article1.png",
    url: "/actualites/nouvelle-application-de-priere-lancee",
    publishedAt: "2024-06-01",
    category: "Technologie",
    country: "France",
    authorName: "Jean Dupont",
    tags: ["application", "prière", "lancement"],
    description: "Salutation du Saint-Père au Patriarche bouddhiste le jeudi 21 novembre 2019 au Temple Wat Ratchabophit Sathit Maha Simaram (Bangkok).",
  },
  {
    id: "2",
    title: "Conférence sur l'innovation religieuse",
    image: "/assets/effata/articles/article10.jpg   ",
    url: "/actualites/conference-innovation-religieuse",
    publishedAt: "2024-06-05",
    category: "Événement",
    country: "Belgique",
    authorName: "Marie Lambert",
    tags: ["conférence", "innovation", "religion"],
  },
  {
    id: "3",
    title: "Lancement d'un podcast chrétien",
    image: "/assets/effata/articles/article3.jpeg",
    url: "/actualites/lancement-podcast-chretien",
    publishedAt: "2024-06-10",
    category: "Média",
    country: "Suisse",
    authorName: "Paul Martin",
    tags: ["podcast", "chrétien", "audio"],
  },
  // 7 autres actualités avec des id uniques
  {
    id: "4",
    title: "Actualité 4",
    image: "/assets/effata/articles/article4.jpg",
    url: "#",
    publishedAt: "2024-06-11",
    category: "Média",
    country: "Suisse",
    authorName: "Paul Martin",
    tags: ["tag1"],
  },
  {
    id: "5",
    title: "Actualité 5",
    image: "/assets/effata/articles/article5.jpg",
    url: "#",
    publishedAt: "2024-06-12",
    category: "Média",
    country: "Suisse",
    authorName: "Paul Martin",
    tags: ["tag1"],
  },
  {
    id: "6",
    title: "Actualité 6",
    image: "/assets/effata/articles/article6.png",
    url: "#",
    publishedAt: "2024-06-13",
    category: "Média",
    country: "Suisse",
    authorName: "Paul Martin",
    tags: ["tag1"],
  },
  {
    id: "7",
    title: "Actualité 7",
    image: "/assets/effata/articles/article7.jpg",
    url: "#",
    publishedAt: "2024-06-14",
    category: "Média",
    country: "Suisse",
    authorName: "Paul Martin",
    tags: ["tag1"],
  },
  {
    id: "8",
    title: "Actualité 8",
    image: "/assets/effata/articles/article8.jpeg",
    url: "#",
    publishedAt: "2024-06-15",
    category: "Média",
    country: "Suisse",
    authorName: "Paul Martin",
    tags: ["tag1"],
  },
  {
    id: "9",
    title: "Actualité 9",
    image: "/assets/effata/articles/article9.jpg",
    url: "#",
    publishedAt: "2024-06-16",
    category: "Média",
    country: "Suisse",
    authorName: "Paul Martin",
    tags: ["tag1"],
  },
  {
    id: "10",
    title: "Actualité 10",
    image: "/assets/effata/articles/article1.png",
    url: "#",
    publishedAt: "2024-06-17",
    category: "Média",
    country: "Suisse",
    authorName: "Paul Martin",
    tags: ["tag1"],
  },
];
