import type { CategoryOption, CuturamaEvent } from "./cuturama.types";

export const ITEMS_PER_PAGE = 9;

export const CATEGORIES: CategoryOption[] = [
    { label: "Tous" },
    { label: "Concerts",   image: "/assets/cuturama/ariso.png" },
    { label: "Cinéma",     image: "/assets/cuturama/ariso.png" },
    { label: "Pèlerinage", image: "/assets/cuturama/ariso.png" },
];

const SHARED_DESCRIPTION = `Une soirée d'adoration acoustique intime avec Geneviève Brou.
Instant Sacré est une expérience musicale intime où la voix profonde de Geneviève Brou rencontre la puissance du gospel dans une atmosphère acoustique et authentique.
Dans le cadre intime et élégant du Cinéma Majestic Ivoire, laissez-vous porter par un moment rare : une parenthèse de musique, de foi et d'émotion où chaque note invite au recueillement et à la présence.
Plus qu'un concert, Instant Sacré est une rencontre — un moment suspendu entre ciel et terre.`;

const SHARED_TICKET_TYPES = [
    { id: "vvp", name: "VVP | 75.000 FCFA", price: 75000 },
    { id: "vip", name: "VIP | 50.000 FCFA", price: 50000 },
    { id: "normale", name: "Normale | 25.000 FCFA", price: 25000 },
];

const MAP_EMBED = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3972.1!2d-3.9833!3d5.3213!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNcKwMTknMTYuNyJOIDPCsDU4JzU5LjkiVw!5e0!3m2!1sfr!2sci!4v1617000000000!5m2!1sfr!2sci";

export const FAKE_EVENTS: CuturamaEvent[] = [
    {
        id: "1",
        slug: "concert-1",
        title: "Concert 1",
        category: "Concerts",
        image: "/assets/cuturama/detail.jpg",
        location: "Palais de la Culture",
        city: "Abidjan, Côte d'Ivoire",
        date: "SAM. 25 AVR. 2026",
        time: "14H00 GMT",
        organizer: "GOSPEL AGENCY",
        organizerDescription: "Gospel Agency est une agence événementielle spécialisée dans les événements culturels et spirituels en Côte d'Ivoire.",
        price: "25.000 FCFA",
        description: SHARED_DESCRIPTION,
        ticketTypes: SHARED_TICKET_TYPES,
        mapEmbedUrl: MAP_EMBED,
    },
    {
        id: "2",
        slug: "cinema-1",
        title: "Cinéma 1",
        category: "Cinéma",
        image: "/assets/cuturama/event-cinema1.jpg",
        location: "Cinéma Majestic Ivoire",
        city: "Abidjan, Côte d'Ivoire",
        date: "SAM. 25 AVR. 2026",
        time: "14H00 GMT",
        organizer: "GOSPEL AGENCY",
        organizerDescription: "Gospel Agency est une agence événementielle spécialisée dans les événements culturels et spirituels en Côte d'Ivoire.",
        price: "25.000 FCFA",
        description: SHARED_DESCRIPTION,
        ticketTypes: SHARED_TICKET_TYPES,
        mapEmbedUrl: MAP_EMBED,
    },
    {
        id: "3",
        slug: "pelerinage-1",
        title: "Pèlerinage 1",
        category: "Pèlerinage",
        image: "/assets/cuturama/event-pelerinage1.jpg",
        location: "Palais de la Culture",
        city: "Abidjan, Côte d'Ivoire",
        date: "SAM. 25 AVR. 2026",
        time: "14H00 GMT",
        organizer: "GOSPEL AGENCY",
        organizerDescription: "Gospel Agency est une agence événementielle spécialisée dans les événements culturels et spirituels en Côte d'Ivoire.",
        price: "25.000 FCFA",
        description: SHARED_DESCRIPTION,
        ticketTypes: SHARED_TICKET_TYPES,
        mapEmbedUrl: MAP_EMBED,
    },
    {
        id: "4",
        slug: "cinema-2",
        title: "Cinéma 2",
        category: "Cinéma",
        image: "/assets/cuturama/event-cinema2.jpg",
        location: "Palais de la Culture",
        city: "Abidjan, Côte d'Ivoire",
        date: "SAM. 25 AVR. 2026",
        time: "14H00 GMT",
        organizer: "GOSPEL AGENCY",
        price: "25.000 FCFA",
        description: SHARED_DESCRIPTION,
        ticketTypes: SHARED_TICKET_TYPES,
        mapEmbedUrl: MAP_EMBED,
    },
    {
        id: "5",
        slug: "cinema-3",
        title: "Cinéma 3",
        category: "Cinéma",
        image: "/assets/cuturama/event-cinema3.jpg",
        location: "Palais de la Culture",
        city: "Abidjan, Côte d'Ivoire",
        date: "SAM. 25 AVR. 2026",
        time: "14H00 GMT",
        organizer: "GOSPEL AGENCY",
        price: "25.000 FCFA",
        description: SHARED_DESCRIPTION,
        ticketTypes: SHARED_TICKET_TYPES,
        mapEmbedUrl: MAP_EMBED,
    },
    {
        id: "6",
        slug: "concert-2",
        title: "Concert 2",
        category: "Concerts",
        image: "/assets/cuturama/event-concert2.jpg",
        location: "Palais de la Culture",
        city: "Abidjan, Côte d'Ivoire",
        date: "SAM. 25 AVR. 2026",
        time: "14H00 GMT",
        organizer: "GOSPEL AGENCY",
        price: "25.000 FCFA",
        description: SHARED_DESCRIPTION,
        ticketTypes: SHARED_TICKET_TYPES,
        mapEmbedUrl: MAP_EMBED,
    },
    {
        id: "7",
        slug: "cinema-2-b",
        title: "Cinéma 2",
        category: "Cinéma",
        image: "/assets/cuturama/event-cinema2.jpg",
        location: "Palais de la Culture",
        city: "Abidjan, Côte d'Ivoire",
        date: "SAM. 25 AVR. 2026",
        time: "14H00 GMT",
        organizer: "GOSPEL AGENCY",
        price: "25.000 FCFA",
        description: SHARED_DESCRIPTION,
        ticketTypes: SHARED_TICKET_TYPES,
        mapEmbedUrl: MAP_EMBED,
    },
    {
        id: "8",
        slug: "concert-1-b",
        title: "Concert 1",
        category: "Concerts",
        image: "/assets/cuturama/event-concert1.jpg",
        location: "Palais de la Culture",
        city: "Abidjan, Côte d'Ivoire",
        date: "SAM. 25 AVR. 2026",
        time: "14H00 GMT",
        organizer: "GOSPEL AGENCY",
        price: "25.000 FCFA",
        description: SHARED_DESCRIPTION,
        ticketTypes: SHARED_TICKET_TYPES,
        mapEmbedUrl: MAP_EMBED,
    },
    {
        id: "9",
        slug: "pelerinage-1-b",
        title: "Pèlerinage 1",
        category: "Pèlerinage",
        image: "/assets/cuturama/event-pelerinage1.jpg",
        location: "Palais de la Culture",
        city: "Abidjan, Côte d'Ivoire",
        date: "SAM. 25 AVR. 2026",
        time: "14H00 GMT",
        organizer: "GOSPEL AGENCY",
        price: "25.000 FCFA",
        description: SHARED_DESCRIPTION,
        ticketTypes: SHARED_TICKET_TYPES,
        mapEmbedUrl: MAP_EMBED,
    },
    {
        id: "10",
        slug: "cinema-2-c",
        title: "Cinéma 2",
        category: "Cinéma",
        image: "/assets/cuturama/event-cinema2.jpg",
        location: "Palais de la Culture",
        city: "Abidjan, Côte d'Ivoire",
        date: "SAM. 25 AVR. 2026",
        time: "14H00 GMT",
        organizer: "GOSPEL AGENCY",
        price: "25.000 FCFA",
        description: SHARED_DESCRIPTION,
        ticketTypes: SHARED_TICKET_TYPES,
        mapEmbedUrl: MAP_EMBED,
    },
    {
        id: "11",
        slug: "cinema-3-b",
        title: "Cinéma 3",
        category: "Cinéma",
        image: "/assets/cuturama/event-cinema3.jpg",
        location: "Palais de la Culture",
        city: "Abidjan, Côte d'Ivoire",
        date: "SAM. 25 AVR. 2026",
        time: "14H00 GMT",
        organizer: "GOSPEL AGENCY",
        price: "25.000 FCFA",
        description: SHARED_DESCRIPTION,
        ticketTypes: SHARED_TICKET_TYPES,
        mapEmbedUrl: MAP_EMBED,
    },
    {
        id: "12",
        slug: "concert-1-c",
        title: "Concert 1",
        category: "Concerts",
        image: "/assets/cuturama/event-concert1.jpg",
        location: "Palais de la Culture",
        city: "Abidjan, Côte d'Ivoire",
        date: "SAM. 25 AVR. 2026",
        time: "14H00 GMT",
        organizer: "GOSPEL AGENCY",
        price: "25.000 FCFA",
        description: SHARED_DESCRIPTION,
        ticketTypes: SHARED_TICKET_TYPES,
        mapEmbedUrl: MAP_EMBED,
    },
];
